baseURL = "/"
languageCode = "ko-kr"
title = "Hyugo's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Hyugo"
  description = "Hyugo's blog"
  github = "jkl2554"
  email = "jkl2554@gmail.com"
  url = "https://github.com/jkl2554/"
  keywords = "blog, Azure, kubernetes"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  location = "Korea"
  userStatusEmoji = "ğŸ˜"
  enableGitalk = true
    
  [params.gitalk]
    clientID = "Your client ID" # Your client ID
    clientSecret = "Your client secret" # Your client secret
    repo = "jkl2554" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "jkl2554" # æ‚¨çš„GitHub ID
    admin = "jkl2554" # æ‚¨çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    
  [[params.links]]
    title = "Link"
    href = "https://github.com/jkl2554"
  [[params.links]]
    title = "Link2"
    href = "https://github.hyugo.org"
    icon = "https://github.hyugo.org/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
